# Generated by Django 2.2 on 2020-02-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneToManyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
